fix: Updated estimate-from-url workflow

diff --git a/.github/workflows/estimateFromUrl.yml b/.github/workflows/estimateFromUrl.yml
--- a/.github/workflows/estimateFromUrl.yml
+++ b/.github/workflows/estimateFromUrl.yml
@@ -1,4 +1,5 @@
-# This is a reusable workflow that can be called from your repository to provide an estimate given specific template/params
+# This is a reusable workflow that can be called from your repository to provide an estimate on a specific template with optional parameter file
+# or inline parameters supplied.
 name: Estimate From Url
 
 on:
@@ -23,7 +24,7 @@ on:
         type: string
       templateParamFileURL:
         description: 'Template parameters file URL'
-        required: true
+        required: false
         type: string
       templateParams:
         description: 'Parameters in Key=Value format. Use spaces to separate multiple params'
@@ -52,7 +53,7 @@ on:
         type: string
       templateParamFileURL:
         description: 'Template parameters file URL'
-        required: true
+        required: false
         type: string
       templateParams:
         description: 'Parameters in Key=Value format. Use spaces to separate multiple params'
@@ -60,6 +61,9 @@ on:
         default: ''
         type: string
     secrets:
+      GH_PAT:
+        description: 'Used together with a internal or private hosted repository in order to read the contents.'
+        required: false
       AZURE_CLIENT_ID:
         required: true
       AZURE_TENANT_ID:
@@ -68,8 +72,8 @@ on:
         required: true
 
 permissions:
-  id-token: write
-  contents: read
+  id-token: write # The reusable workflow needs to be able to fetch token to log in to Azure.
+  contents: read # The reusable workflow needs to be able to read the contents of the repository (used with a public hosted repository).
 
 concurrency: "${{ inputs.environment }}-${{ inputs.rg }}"
 
@@ -78,7 +82,7 @@ jobs:
     runs-on: ubuntu-latest
     environment: ${{ inputs.environment }}
     steps:
-    - uses: robinraju/release-downloader@v1.5
+    - uses: robinraju/release-downloader@v1.8
       name: Download Arm-Estimator release
       id: downloadACE
       with:
@@ -87,56 +91,88 @@ jobs:
         #latest: ${{ inputs.aceVersion == 'latest' }}
         #tag: ${{ (inputs.aceVersion != 'latest' && inputs.aceVersion) || '' }}
         tag: ${{ inputs.aceVersion }}
-        fileName: "ace-linux-x64*.zip"
+        fileName: "linux-x64*.zip"
         
     - name: Unzip and prepare ACE
       run: |
         echo ${{steps.downloadACE.outputs.tag_name}}
-        ACEZIP="ace-linux-x64.zip"
+        ACEZIP="linux-x64.zip"
         echo $ACEZIP
         unzip $ACEZIP
         chmod +x ./azure-cost-estimator
 
-    - uses: azure/login@v1.4.6
+    - uses: azure/login@v1.5.0
       name: Login to Azure
       with:
         client-id: ${{ secrets.AZURE_CLIENT_ID }}
         tenant-id: ${{ secrets.AZURE_TENANT_ID }}
         subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
         
-    - name: Prepare/Check Arm Assets
-      id: armassets
+    - name: Prepare/Check template assets
+      id: templateassets
       env:
-        templateURL: ${{ inputs.templateFileURL}}
-        paramsURL: ${{ inputs.templateParamFileURL}}
+        templateURL: ${{ inputs.templateFileURL }}
+        paramsURL: ${{ inputs.templateParamFileURL }}
       run: |
-        echo "Downloading arm template"
-        curl -O $templateURL -L
-
-        echo "Downloading param file"
-        curl -O $paramsURL -L
-        
-        ls -l
-        
-        echo "template=${templateURL##*/}" >> $GITHUB_OUTPUT
-        echo "params=${paramsURL##*/}" >> $GITHUB_OUTPUT
-        
+        templateFileName=${templateURL##*/}
+    
+        echo "Downloading template: $templateFileName"
+        curl -O $templateURL -L -H "Authorization: Token ${{ secrets.GH_PAT }}"
+        if [ $? -ne 0 ]; then
+          echo "Failed to download the template."
+          exit 1
+        fi
+      
+        if [ ! -z $paramsURL ]; then
+          paramsFileName=${paramsURL##*/}
+          echo "Downloading parameter file: $paramsFileName"
+          curl -O $paramsURL -L -H "Authorization: Token ${{ secrets.GH_PAT }}"
+          if [ $? -ne 0 ]; then
+            echo "Failed to download the parameter file."
+            exit 1
+          fi
+      
+          ls -l
+      
+          echo "template=$templateFileName" >> $GITHUB_OUTPUT
+          echo "params=$paramsFileName" >> $GITHUB_OUTPUT
+        else
+          ls -l
+      
+          echo "template=$templateFileName" >> $GITHUB_OUTPUT
+        fi
+  
     - name: Estimate
       id: ace
       env:
-        templateParams: ${{ inputs.templateParams}}
-      run: |             
-        if [ ! -z "$templateParams" ]
-        then 
+        templateParams: ${{ inputs.templateParams }}
+      run: |
+        if [ -n "$templateParams" ]; then 
           templateParamsInlined=$(echo --inline ${templateParams//[' ']/ --inline })
         fi
-        
-        echo "Estimating template ${{ steps.armassets.outputs.template }} with params file ${{ steps.armassets.outputs.params }} and inline params $templateParamsInlined - deploying into rg ${{ inputs.rg }}"
-        ./azure-cost-estimator ${{ steps.armassets.outputs.template }} ${{ secrets.AZURE_SUBSCRIPTION_ID }} ${{ inputs.rg }} --parameters ${{ steps.armassets.outputs.params }} $templateParamsInlined --generateJsonOutput --jsonOutputFilename estimate
-        
+      
+        ls
+      
+        template="${{ steps.templateassets.outputs.template }}"
+        rg="${{ inputs.rg }}"
+      
+        if [ -n "${{ steps.templateassets.outputs.params }}" ]; then
+          params="${{ steps.templateassets.outputs.params }}"
+          echo "Estimating template $template with parameter file $params and inline parameters $templateParamsInlined - deploying into resource group $rg"
+          ./azure-cost-estimator $template ${{ secrets.AZURE_SUBSCRIPTION_ID }} $rg --parameters $params $templateParamsInlined --generateJsonOutput --jsonOutputFilename estimate
+        else
+          if [ -n "$templateParamsInlined" ]; then
+            echo "Estimating template $template with inline parameters $templateParamsInlined - deploying into resource group $rg"
+            ./azure-cost-estimator $template ${{ secrets.AZURE_SUBSCRIPTION_ID }} $rg $templateParamsInlined --generateJsonOutput --jsonOutputFilename estimate
+          else
+            echo "Estimating template $template - deploying into resource group $rg"
+            ./azure-cost-estimator $template ${{ secrets.AZURE_SUBSCRIPTION_ID }} $rg --generateJsonOutput --jsonOutputFilename estimate
+          fi
+        fi
+      
         ls
         
-    - uses: actions/upload-artifact@v3.1.2
+    - uses: actions/upload-artifact@v3.1.3
       name: Save Estimate Artifact
       with:
         name: estimate
